name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Run GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:PackageVersion=${{ steps.gitversion.outputs.majorMinorPatch }}

    - name: Push
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: 'src/CryptoBuddy/CryptoBuddy.csproj'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}